# Generated by Django 4.2.16 on 2024-11-03 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи', verbose_name='Дата обновления')),
                ('image', models.ImageField(help_text='Загрузите изображение напитка', upload_to='images/drinks/', verbose_name='Изображение')),
                ('title', models.CharField(help_text='Введите название напитка', max_length=100, verbose_name='Название')),
                ('description', models.TextField(help_text='Введите описание напитка', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену напитка', max_digits=10, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, если напиток активен', verbose_name='Активный')),
                ('category', models.ForeignKey(help_text='Выберите категорию для напитка', on_delete=django.db.models.deletion.CASCADE, to='menu.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(help_text='Выберите теги для напитка', to='menu.tags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
            },
        ),
    ]
