# Generated by Django 4.2.16 on 2024-11-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_image', verbose_name='Изображение')),
                ('title', models.CharField(help_text='Введите заголовок о нас', max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите текст о нас', verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок', max_length=150, verbose_name='Заголовок')),
                ('address', models.CharField(help_text='Введите адрес', max_length=150, verbose_name='Адрес')),
                ('map_location', models.URLField(help_text='Введите URL для отображения на карте', verbose_name='Расположение на карте')),
                ('working_hours', models.CharField(help_text='Введите рабочие часы', max_length=100, verbose_name='Рабочие часы')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Введите номер телефона', max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(help_text='Введите электронную почту', max_length=254, verbose_name='Электронная почта')),
                ('whatsapp_url', models.URLField(help_text='Введите URL для WhatsApp', verbose_name='URL WhatsApp')),
                ('telegram_url', models.URLField(help_text='Введите URL для Telegram', verbose_name='URL Telegram')),
                ('instagram_url', models.URLField(help_text='Введите URL для Instagram', verbose_name='URL Instagram')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
